server:
  port: 80
spring:
  application:
    name: paymentconsul-order-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
      #hostname: 127.0.0.1