server:
  port: 83
spring:
  application:
    name: nacos-consumer01
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
#消费者将要去访问注册中心中的微服务名称
service-url:
  nacos-user-service: http://nacos-provider-payment