server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  #服务端实列名称
  client:
    register-with-eureka: false  #flase表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，维护服务实列，不需检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/ #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址