server:
  port: 9004
spring:
  application:
    name:  alibaba-provider-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"